### ISSUE TITLE
Your web app is ready! 🚀

### ISSUE THREAD

**Issue by sleepingexperiments** [ADILAYOUB/100_flutter_challange#5]
Hey! 👋

Someone has requested a demo of your project using [Ukoreh](https://ukoreh.fun/)! 🧙‍♂️.

The app compiled fine and is now live at https://flutter-preview.github.io/ADILAYOUB-100_flutter_challange

**Comment by ADILAYOUB** [comment]
Deployed app https://github.com/ADILAYOUB/100_flutter_challange/tree/14

**Comment by ADILAYOUB** [comment]
Deployed app https://github.com/ADILAYOUB/100_flutter_challange/tree/14
